### ISSUE TITLE
Allow every n minutes with offset.

### ISSUE THREAD

**Issue by captncraig** [schyntax/schyntax#11]
Lets say I want to run every 5 minutes starting at 1. so 12:01, 12:05, 12:11 ...

I can't find a way to do this at present. `minutes(*%5)` will run on even increments of 5 minutes, but I can't define an offset. 

I'm not sure what syntax would work for this. Maybe `minutes(1+*%5)` or `m(*%5+1)` , or even `m(1,6...)`. Any other ideas?

**Comment by captncraig** [comment]
I would use this to somewhat space out events so they don't all happen at once. 

Some events can run a 1,6,11... and others at 2,7,12... etc.

**Comment by bretcope** [comment]
Use `min(1%5)` which technically expands to `min(1..59%5)`. You can also use a seconds offset if you don't need the offset to be in full minutes, e.g. `min(*%5) sec(30)`.

**Comment by captncraig** [comment]
gotcha. That makes sense to me now. Thanks!
