### ISSUE TITLE
Suggestion: Syntax minutes(%5+3)  for task to run at minutes: 3, 8, 13, 18, etc.

### ISSUE THREAD

**Issue by kiprobinson** [schyntax/schyntax#4]
Just a suggestion. In the past I've had to do something like:  TaskA and TaskB run every 5 minutes, but they alternate. i.e.:

TaskA: 0, 10, 20, 30, 40, 50
TaskB: 5, 15, 25, 35, 45, 55

TaskB has been kind of a pain to schedule with other systems. Here would be my suggested syntax:

TaskA: minutes(%10)
TaskB: minutes(%10+5)

The +5 means, take times that match %10, and add 5 minutes to it.

**Comment by bretcope** [comment]
You can already do this:

Task A: `minutes(*%10)` or `minutes(0%10)`
Task B: `minutes(5%10)`

The `*` always expands to the `min..max` for the given expression. Don't forget that the `*` is required. `mintues(%10)` is not valid.

A single value, like `5`, doesn't normally expand, but when you apply an interval to it, it expands to `val..max`. So, `minutes(5%10)` is the same as `minutes(5..59%10)`. I've been considering whether it should really expand to `minutes(5..4%10)`, but for most schedules it's effectively the same, and if you're worried about it, you can always set the range explicitly.
