### ISSUE TITLE
Adding tests for exceptional cases

### ISSUE THREAD

**Issue by nchidsey** [schyntax/schyntax#6]
Currently, the `tests.json` test suite only has the ability to test successful input strings.  To add tests for bad syntax, or schedules with no valid solution, the json structure needs some modification.  At first thought, it seems the error cases need to be specific to parsing, next and/or previous methods.  For example, `minutes(` is an error at parse time, while `minutes(5, !5)` parses but has no solutions, and `dates(1999/1/1)` has a previous solution but not a next.

Perhaps for parse-time errors, a language-agnostic error name could be added as an additional key, and errors for previous and next calls could put the error name in the previous or next value instead of the time.

E.g.

``` json
      {
        "format": "minutes(",
        "parseError": "SchyntaxParseException"
      },
      {
        "format": "{}",
        "parseError": "InvalidScheduleException"
      },
      {
        "format": "date(1999/1/1)",
        "date": "2014-06-25T18:26:00.000Z",
        "prev": "1999-01-01T00:00:00.000Z",
        "next": "ValidTimeNotFoundException"
      },
```

(I didn't use very agnostic error names, but you get the idea)

**Comment by bretcope** [comment]
I agree there should be parse error tests, and more tests in general, especially for abnormal input.

The `InvalidScheduleException` is only being used in one place, and it should probably just be converted to a parse error at index 0.

As for the JSON tests, the structure I would propose is:

```
{
  "format": string,
  "date": iso8601,
  "next": iso8601,
  "prev": iso8601,
  "parseErrorIndex": integer
}
```

`parseErrorIndex`, `next`, and `prev` would be optional. If next or prev is missing, then a valid time is not expected. I definitely wouldn't have prev/next sometimes be a date and sometimes be a string, because that's going to make parsing the JSON messy.

**Comment by nchidsey** [comment]
Making the existing use of `InvalidScheduleException` into a parse error makes sense, but perhaps it could be used in the parser stage, not the validation stage.  In that case, effectively the language definition of a group for example would be curly braces with one or more expressions, and the index would be more precise.  For example, parsing `"{}"` would be an error at the closing curly brace at index 1 instead of 0.  As a side effect, this would also catch `"min(*) {}"` as an error at index 8, where the current implementation would allow it.

**Comment by bretcope** [comment]
Closing this. I think I'll handle the parse changes of `{}` in another issue.

**Comment by bretcope** [comment]
I've made an issue to disallow mixing groups and top-level expressions though (see #9).

I'm a bit undecided on whether or not `{}` should be a parse error (assuming there are other groups with valid expressions). I'm leaning towards not making it a parse error for two reasons:
1. In programming languages, and empty block is typically valid, even if unusual.
2. If the language ever supports comments (seems likely), it may be handy to comment out some or all of the individual expressions in a group without having to comment out the braces too every time the last expression is toggled.

I think I'm going to punt on the issue. It's not really causing problems as-is.
